test and debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,7 @@ jobs:
     runs-on: arc-runner-set-oke-org-poc
     # runs-on: arc-runner-set-oke-org-nv-ai-bp
     env:
+      DOCKER_IMG_NAME: nvcr.io/nvidia/rapidsai/notebooks:25.06-cuda12.8-py3.12
       DOCKER_COMPOSE_FILE: ./docker/brev/docker-compose-nb-2504.yaml 
       NOTEBOOK_PATH: ./notebooks/01_scRNA_analysis_preprocessing.ipynb
       PYTHON_VERSION: 3.12
@@ -83,7 +84,12 @@ jobs:
       - name: Pull large image first
         run: |
           # export COMPOSE_HTTP_TIMEOUT=600
-          docker pull nvcr.io/nvidia/rapidsai/notebooks:25.06-cuda12.8-py3.12
+          docker pull "DOCKER_IMG_NAME" || (
+            echo "Pull failed, retrying..." 
+            sleep 30
+            docker pull --quiet "DOCKER_IMG_NAME"
+          )
+        timeout-minutes: 15
 
       - name: Start container
         run: |
@@ -92,7 +98,8 @@ jobs:
           
           export COMPOSE_HTTP_TIMEOUT=300
           export NOTEBOOKS_HOST_PATH="${{ github.workspace }}"
-          docker compose --verbose -f "$DOCKER_COMPOSE_FILE" up -d
+
+          docker compose --verbose -f "$DOCKER_COMPOSE_FILE" up -d --wait
 
       - name: Debug container logs
         if: ${{ failure() }}
@@ -100,7 +107,8 @@ jobs:
           docker ps -a
           # docker system df
           # docker stats
-          docker logs brev_backend_1
+          # docker logs brev_backend_1
+          # docker compose -f "$DOCKER_COMPOSE_FILE" logs --tail=50
 
       - name: Check running containers
         run: docker ps -a
@@ -111,13 +119,9 @@ jobs:
           docker-compose -f "$DOCKER_COMPOSE_FILE" config --services
           docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend pwd
           docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend ls -al .
-          docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend find . -maxdepth 3 | sed -e 's|[^/]*/|- |g' -e 's|^\./||'
+          docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend find . -maxdepth 2 | sed -e 's|[^/]*/|- |g' -e 's|^\./||'
           echo "=============Debug Info======================"
 
-      - name: Stop containers
-        if: ${{ always() }}
-        run: docker-compose -f "$DOCKER_COMPOSE_FILE" down
-          
       - name: Run Jupyter Notebook
         env:
           NGC_API_Key: ${{ secrets.NGC_API_KEY }}
@@ -174,3 +178,8 @@ jobs:
       #     name: result-notebook
       #     path: "result.html"
       #     retention-days: 30
+
+      - name: Stop containers
+        if: ${{ always() }}
+        run: docker-compose -f "$DOCKER_COMPOSE_FILE" down
+          
