enable docker image cache for pulling image. to save time

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,7 @@ jobs:
     # runs-on: arc-runner-set-oke-org-nv-ai-bp
     env:
       DOCKER_IMG_NAME: "nvcr.io/nvidia/rapidsai/notebooks:25.06-cuda12.8-py3.12"
+      DOCKER_IMG_CACHE_NAME: "rapidsai_notebooks_25.06-cuda12.8-py3.12"
       DOCKER_COMPOSE_FILE: "./docker/brev/docker-compose-nb-2504.yaml"
       NOTEBOOK_PATH: "./notebooks/01_scRNA_analysis_preprocessing.ipynb"
       PYTHON_VERSION: "3.12"
@@ -81,15 +82,35 @@ jobs:
           docker version
           docker compose version
 
-      - name: Pull large image first
+
+      - name: Cache Docker image
+        id: cache-docker-image
+        uses: actions/cache@v3
+        with:
+          path: /tmp/docker-pull-cache
+          key: ${{ runner.os }}-docker-${{ hashFiles('$DOCKER_COMPOSE_FILE') }}
+
+      - name: Check cache size
+        run: |
+          du -sh /tmp/docker-pull-cache
+          echo "Cache Key: ${{ steps.cache-docker-image.outputs.cache-primary-key }}"
+
+      - name: Load docker image from cache or Pull it
         run: |
           start_time=$(date +%s)
           echo "Docker image will use: $DOCKER_IMG_NAME"
-          docker pull "$DOCKER_IMG_NAME" || (
-            echo "Pull failed, retrying..." 
-            sleep 30
-            docker pull --quiet "$DOCKER_IMG_NAME"
-          )
+
+          if [ -f "/tmp/docker-pull-cache/$DOCKER_IMG_CACHE_NAME.tar" ]; then
+            docker load -i /tmp/docker-pull-cache/$DOCKER_IMG_CACHE_NAME.tar
+          else
+            docker pull "$DOCKER_IMG_NAME" || (
+              echo "Pull failed, retrying..." 
+              sleep 30
+              docker pull --quiet "$DOCKER_IMG_NAME"
+            )
+            mkdir -p /tmp/docker-pull-cache
+            docker save $DOCKER_IMG_NAME > /tmp/docker-pull-cache/$DOCKER_IMG_CACHE_NAME.tar
+          
           end_time=$(date +%s)
           echo "Execution time: $((end_time - start_time)) seconds"
         timeout-minutes: 15
@@ -144,7 +165,7 @@ jobs:
           docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend python --version
           docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend python3 --version
 
-          docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend pip install ipykernel papermill scanpy
+          docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend pip install -r requirements.txt
           # docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend python -m ipykernel install --user --name python3 --display-name "python3"
           docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T backend jupyter kernelspec list
 
