add .pre-commit

diff --git a/.github/workflows/notebook_runner.yml b/.github/workflows/notebook_runner.yml
--- a/.github/workflows/notebook_runner.yml
+++ b/.github/workflows/notebook_runner.yml
@@ -46,7 +46,7 @@ jobs:
           ]
       max-parallel: 4
       fail-fast: false
-    
+
     env:
       DEPLOY_ENV: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}
 
@@ -66,7 +66,7 @@ jobs:
       OUTPUT_PYTEST_RESULT_XML: "pytest_result_${{ matrix.NOTEBOOK_FILENAME }}.xml"
       OUTPUT_PYTEST_REPORT_HTML: "pytest_report_${{ matrix.NOTEBOOK_FILENAME }}.html"
       ARTIFACT_DIR: "${{ github.workspace }}/test-results/${{ matrix.NOTEBOOK_FILENAME }}"
-    
+
     steps:
       - name: Set global vars
         id: set_global_vars
@@ -197,7 +197,7 @@ jobs:
 
           echo "[Info]: the docker image cache does NOT exists, just pull it from remote"
           if ! docker pull "$DOCKER_IMG_NAME:$DOCKER_IMG_TAG"; then
-            echo "Pull failed, retrying..." 
+            echo "Pull failed, retrying..."
             sleep 10
             docker pull --quiet "$DOCKER_IMG_NAME:$DOCKER_IMG_TAG" || {
               echo "Error: Docker pull failed after retry"
@@ -299,7 +299,7 @@ jobs:
                       echo "Maximum retry attempts ($MAX_RETRIES) reached. Proceeding with subsequent commands."
                   fi
               fi
-          done         
+          done
 
           pip install jupyter papermill pytest-html pytest-cov
 
@@ -365,7 +365,7 @@ jobs:
 
           docker compose -f "$DOCKER_COMPOSE_FILE" exec -T backend bash -c '
             echo "===jupyter_nbconvert logs==="
-            cat "$DOCKER_WRITEABLE_DIR/jupyter_nbconvert.log" 
+            cat "$DOCKER_WRITEABLE_DIR/jupyter_nbconvert.log"
 
             echo "===============Check file====================="
             if [ -s "$DOCKER_WRITEABLE_DIR/$OUTPUT_NOTEBOOK_HTML" ]; then
@@ -463,7 +463,7 @@ jobs:
         run: |
           SCRIPT_FILE=$(mktemp)
           cat > $SCRIPT_FILE <<'EOS'
-          set -euxo pipefail  # 增加详细日志
+          set -euxo pipefail
           cd blueprint-github-test
 
           OUTPUT_NOTEBOOK_HTML="$1"
@@ -475,10 +475,10 @@ jobs:
 
           export PATH="/home/rapids/.local/bin:$PATH"
           python -m pip install --upgrade pip
-          curl -sSL https://install.python-poetry.org | python3 - 
+          curl -sSL https://install.python-poetry.org | python3 -
 
           poetry config virtualenvs.create true
-          poetry install --no-interaction --no-root 
+          poetry install --no-interaction --no-root
 
           if [ -d "cloudia" ]; then
             pushd cloudia
@@ -570,7 +570,7 @@ jobs:
           echo "$TEST_OUTPUT" >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
         shell: bash
-      
+
       - name: Copy result files from container to runner
         id: prepare-result-file
         if: >
@@ -711,4 +711,3 @@ jobs:
           echo "- ⚠️ Unexpected Passes (XPassed): $total_xpassed" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
           echo "📊 [View Detailed Artifacts]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> $GITHUB_STEP_SUMMARY
-
